Repository hmcts/sscs-track-your-appeal-frontend, pull requests merged in 2020-02, with the labels that each got.

#156 copy changes for appeal received
  app/assets/locale/en.json
Labels: ns:sscs, ns:sscs-tya-frontend-pr-156, rel:sscs-tya-frontend-pr-156

#168 SSCS-7180 TYA-Add contact email and change opening times to TYA contact us section
  app/assets/locale/en.json
  app/views/contact-us.html
  test/e2e/functional/page/contactUs.test.js
Labels: ns:sscs, rel:sscs-tya-frontend-pr-168

#169 increase timeout
  .gitignore
  test/e2e/codecept.conf.js
Labels: ns:sscs, rel:sscs-tya-frontend-pr-169

#170 SSCS-7306 remove deprecated terraform method
  Jenkinsfile_CNP
  package.json
  test/mock/data/oral/appealReceived.json
  test/mock/data/oral/dormant.json
  test/mock/data/oral/dwpRespond.json
  yarn.lock
Labels: ns:sscs, rel:sscs-tya-frontend-pr-170
