Repository hmcts/sscs-track-your-appeal-frontend, pull requests merged in 2020-01, with the labels that each got.

#162 fix functional test
  test/e2e/functional/aat-env-test-data/SSCS_Extract_Delta_2018-07-09-16-14-19.xml
  test/mock/data/oral/appealReceived.json
  test/mock/data/oral/dormant.json
  test/mock/data/oral/dwpRespond.json
Labels: ns:sscs, rel:sscs-tya-frontend-pr-162

#160 Update dependencies and use devDependencies correctly
  .dockerignore
  .gitignore
  Dockerfile
  Gruntfile.js
  app.js
  config/custom-environment-variables.json
  config/default.json
  docker-compose.yml
  infrastructure/main.tf
  kk
  package.json
  yarn.lock
Labels: ns:sscs, rel:sscs-tya-frontend-pr-160

#166 Move legacy gov.uk modules back to dependencies
  package.json
Labels: ns:sscs, rel:sscs-tya-frontend-pr-166

#165 Fix security issues
  Makefile
  app.js
  app/core/ErrorHandling.js
  package.json
  yarn.lock
Labels: ns:sscs, rel:sscs-tya-frontend-pr-165
